---
spring:
  profiles: default
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false
server:
  port: 7000
  
  
