---
ping-server: google.com
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/tokendb;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    cloud:
    bus:
      enabled: true
  
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
  kafka:
    consumer:
      enable-auto-commit: true
      bootstrap-servers: 127.0.0.1:9092, 127.0.0.1:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "token"  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0
