---
ping-server: google.com
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
spring:
  profiles: default

server:
  port: 0
