---
ping-server: google.com
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/userdb;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0
